SUPABASE_URL = "https://fxriqpzewclplsbjnlia.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cmlxcHpld2NscGxzYmpubGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjYzMzgsImV4cCI6MjA2NTQwMjMzOH0.gTLp8BwUxRiZsSeD13JgiilQSPtmlb1DiP6bfl36I2o"
EMAIL_ADDRESS = "phoenixboysgay@gmail.com"
EMAIL_PASSWORD = "sxor fzha alrr tbsj"
EMAIL_SENDER = "ritvikacebot@gmail.com"
EMAIL_PASSWORD2 = "lqvo dheq shsg huku"
EMAIL_RECEIVER = "mailtosinghritvik@gmail.com"
